### PR TITLE
adding google playstore strings

### PR DESCRIPTION
**Pull request by Gozzwip**

### CODE REVIEW

**Comment by tibbi** [comment]
Hey, update the short description on line 196 too please (the one which wasnt modified by this commit). It is 82 characters long, but 80 is the max :) Thanks

**Comment by Gozzwip** [comment]
Sorry for that issue. I am too lazy and just copied it from camera. So I
forgot changing camera to calendar. Now fixed it and deleted a word which
is not important that much.

15 mar 2018 6:30 PM tarixində, "Tibor Kaputa" <notifications@github.com>
yazıb:

**Comment by tibbi** [comment]
but you were supposed to make that string shorter, not longer :)

**Comment by Gozzwip** [comment]
It's 81 now... Gonna check what can I do for this

15 mar 2018 6:43 PM tarixində, "Tibor Kaputa" <notifications@github.com>
yazıb:

**Comment by tibbi** [comment]
line 196 is the problematic one, "Hadisələri, dəyişdirilə bilən widgeti olan, reklam ehtiva etməyən sadə bir kalendar."

**Comment by Gozzwip** [comment]
Ohhh ok

15 mar 2018 6:54 PM tarixində, "Tibor Kaputa" <notifications@github.com>
yazıb:

**Comment by Gozzwip** [comment]
Done

15 mar 2018 6:54 PM tarixində, "Tibor Kaputa" <notifications@github.com>
yazıb:

**Comment by tibbi** [comment]
hah ye, looks good now. Thanks

**Pull request merged**
