### PR TITLE
Fixed crash while creating monthly widget

### PR DESCRIPTION
**Pull request by Aga-C**
Hi,

I've found that it was impossible to create a monthly widget. Here is a fix for it.

BTW. These new colors (for past events and next month events) on monthly widget are too bright, it would look better if they would be the same as in the app.

**Before:**

https://user-images.githubusercontent.com/85929121/155964464-59d74cc9-ac70-44c5-96b5-271b7ebb00e2.mp4

**After:**

https://user-images.githubusercontent.com/85929121/155964479-07c3bd00-7d79-4b43-ba35-f3387061c913.mp4

### CODE REVIEW

**Comment by tibbi** [comment]
how to reproduce the crash? What should be done?

**Comment by Aga-C** [comment]
I've just updated the app on my phone. After seeing strangely bright colors on the monthly widget, I decided to remove it and add again, but it was impossible to add it. Everything's shown in `Before` video - just try to create a new monthly widget.

**Comment by tibbi** [comment]
if you reinstall the app, does it still crash?

**Comment by Aga-C** [comment]
Yes.

**Comment by tibbi** [comment]
okay, fixed it without findViewById to make it nicer. Thanks though

**Comment by Aga-C** [comment]
You could just write a comment, I'd change it in a short while.

**Comment by tibbi** [comment]
sometimes it is just easier to change the code myself instead of checking what changed in the PR

**Pull request closed without merging**
