### PR TITLE
Feature rfc5545 classification

### PR DESCRIPTION
**Pull request by jatoko**
Added support to decide on the access level of an event in shared calendars https://github.com/SimpleMobileTools/Simple-Calendar/issues/1022.

Added support for:
- RFC5545#section-3.8.1.3 Classification together with ICS import & export
- CalDav accessLevel

Integrated support in:
- Event editor
- Global settings

Tested:
- [x] ICS Import
- [x] ICS Export
- [x] CalDav Sync with Nextcloud calendar implementation

Screenshots:
Event Editor

Settings

Settings Choice

### CODE REVIEW

**Comment by tibbi** [comment]
Umm thanks for the effort I guess, but I dont want to have this implemented just yet as I havent done any research on it and not even Google Calendar contains such a field. It feels too geeky, not for my target audience. Out of that million users only 1 guy reported it, as I wrote it at the linked Github issue too. If you dont want to share an event, just add it at some other calendar. The code itself would need a lot of work to make it fit into my coding style, not to talk about the conflicts you created.

**Comment by jatoko** [comment]
I forgot the rebase, sorry :/ I just solved the issues and was about to reopen.
I disagree that it is geeky feature, and [google calendar](https://support.google.com/calendar/answer/34580?co=GENIE.Platform%3DDesktop&hl=en) does support it for shared calendars. Its common that calendars are shared with others in company settings, but collegues are just allowed to see that one is busy but not the details of an event. This usecase cannot be covered by using different calendars.

I agree on code style, though I did not see which rules you follow :) I just copied a lot of the existing code to not mess up but I would gladly adapt the code to your style further.

**Comment by tibbi** [comment]
I appreciate it, but I dont want to add such a feature for now. Ill see in the future.

**Comment by madb1lly** [comment]
Hi @jatoko,
Thanks for attempting to include these features, I agree with you that they're important.
Cheers 🙂

**Comment by jatoko** [comment]
Hey @madb1lly ,
I try to keep the respective [feature branch](https://github.com/jatoko/Simple-Calendar/tree/feature_rfc5545_classification) of my fork up-to-date with this repos' master branch. Plase feel free to pull and build the APK.

**Comment by madb1lly** [comment]
Thanks @jatoko, if I get chance I'll give it a go.
Cheers 🙂

**Pull request closed without merging**
