### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Anke**
I translated the following lines to German:
13
14
88
95
105
106
110
185
186
187
188
189
190
191
205
241
243
245
247
249
255-272
274
276

The only German terms missing here, are in lines 107-109, because it is unclear in which context the terms "Going", "Not going" and "Maybe going" are being used. Since that part is about attendees, the term "going" could mean something like "possible" or "leaving". Translating the wrong meaning could end up sounding rather ridiculous.

Anka

### CODE REVIEW

**Comment by tibbi** [comment]
those strings are in the context of attendance indeed, so "going" means that the person will attend the event. Thanks

**Comment by Anke** [comment]
Sorry for asking again. I need to know how to conjugate the verbs and I can't reproduce this, as there are no attendance options in my calendar.

The string names in the attendee section are "add_another_attendee", then "my_status". Are the following strings "going/not_going/maybe_going" referring to **another invited attendee** or to **my status**? 

In other words: Does "going" mean, I am attending or he/she is attending? Or are those variables actually applying to both cases?

**Comment by tibbi** [comment]
Attendance is visible only at CalDAV synced events once you add an attendee. Those textual statuses are related to myself only, the attendance of others is marked with a colored icon. Im attaching an image, the other person would have a status color at the bottom right corner of his image, in case he already set any satus.
Screenshot_20190530-170934

**Comment by Anke** [comment]
I see. THX.
Isn't this usually called "Online-Status"? Like "online", "offline" or "online status hidden"?

**Comment by tibbi** [comment]
it has nothing to do with being online or not, but joining the meeting. Just check Google Calendar how is it translated there

**Comment by Anke** [comment]
Okay, I completed the translation. Thank you for your patient help.

**Pull request merged**
