### PR TITLE
Updated German translation.

### PR DESCRIPTION
**Pull request by Atalanttore**
Translated newly added strings to german.

### CODE REVIEW

**Comment by tibbi** [comment]
@Atalanttore a guy reported that the app names like `Schlichte Gallery` or so sound bad, like something stupid or crappy. He says that `Einfache Gallery` sounds better. Any ideas on that? I cannot really device. Thanks

**Comment by tibbi** [comment]
@be-we so you advise using Einfach, right?

**Comment by be-we** [comment]
In my opinion yes.

**Comment by ouzowtf** [comment]
But Einfach could also mean not very feature rich or not very polished.
And these are things I wouldn't use to describe your very nice app :grinning:

**Comment by tibbi** [comment]
well ye, initially I wanted to keep it low on features, but it somehow got out of control :)

**Comment by tibbi** [comment]
So, another guy reported that the translation of "Import contact birthdays" could be also misleading. Currently it is "Kontaktgeburtstage hinzufügen", he suggests "Kontakt zu Jahrestagen hinzufügen". Does it make sense?

**Comment by ouzowtf** [comment]
No, it does not make any sense. This would be like "add contact to anniversary".

**Comment by Atalanttore** [comment]
"Import contact birthdays" translates as "Geburtstage von Kontakten importieren".

**Comment by tibbi** [comment]
ye I mixed up birthdays and anniversaries now, but ignore that. So which one is better,the current  "Kontakt zu Jahrestagen hinzufügen" or a new suggestion "Jahrestage der Kontakte hinzufügen"?

**Comment by ouzowtf** [comment]
Generally "Jahrestage der Kontakte hinzufügen" is better, but it should be similar with the other options for holidays and .ics-import.
Do you want to use "import" or "add"?

import:
"Feiertage importieren"
"Geburtstage der Kontakte importieren"
"Jahrestage der Kontakte importieren"
"Termine der .ics-Datei importieren"

add:
"Feiertage hinzufügen"
"Geburtstage der Kontakte hinzufügen"
"Jahrestage der Kontakte hinzufügen"
"Termine der .ics-Datei hinzufügen"

While we're at it:

Your "Filter events by type" should be "Termine nach Typ filtern" instead of "Termine nach Typ sortieren" in German, because there is no sorting.

**Comment by tibbi** [comment]
holidays, birthdays and anniversaries should be "Add", just .ics files have "Import" also in english, so lets stick to that. Fix the filtering string too please with a new pull request. Thanks

**Pull request merged**
