### PR TITLE
Updata italian translation

### PR DESCRIPTION
**Pull request by ema-pe**

### CODE REVIEW

**Comment by tibbi** [comment]
Hey, not sure how are you finding new strings, but in case you are interested I wrote a guide about setting up emails, so in case some string gets added or updated, you get an email notification. It is at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-get-notified-if-a-translated-file-changes . Thanks

**Comment by ema-pe** [comment]
Hi, I'm using github-file-watcher.com. There is only a problem: it's hard to find exactly new or modified strings, I need to analyze all commits done after mine.

On 23 October 2018 20:55:18 CEST, Tibor Kaputa <notifications@github.com> wrote:
>Hey, not sure how are you finding new strings, but in case you are
>interested I wrote a guide about setting up emails, so in case some
>string gets added or updated, you get an email notification. It is at
>https://github.com/SimpleMobileTools/General-Discussion#how-can-i-get-notified-if-a-translated-file-changes
>. Thanks

-- 
Emanuele

Sent from my mobile, excuse my brevity.

**Comment by tibbi** [comment]
You dont, just press the proper link at the email to get to the commit, there you can find easily what actually changed.

**Comment by ema-pe** [comment]
Thanks for the tip, have a good day!

**Pull request merged**
