### PR TITLE
Fix all-day CalDAV event import for local TZ > GMT+5

### PR DESCRIPTION
**Pull request by angelsl**
I'm not sure if this will affect whatever bug was being fixed in 91d5c3dd00e16320ede02b71ca07eb7acd1f9fa7.

### CODE REVIEW

**Comment by tibbi** [comment]
so with the old version if I set the timezone to more than +5 and use Google sync, I can reproduce some issue? All-day sync is apparently still having issues as Google, Yahoo, NextCloud, Microsoft etc do things a bit differently and whatever I fix, something else breaks.

**Comment by angelsl** [comment]
> so with the old version if I set the timezone to more than +5 and use Google sync, I can reproduce some issue?

Yeah (see #368, I debugged the issue there).

> All-day sync is apparently still having issues as Google, Yahoo, NextCloud, Microsoft etc do things a bit differently and whatever I fix, something else breaks.

Hmm, do you have some examples of how each sync adapter represents all-day events? Maybe we can work this out.

**Comment by tibbi** [comment]
I havent really written down how does it look like at which service, I will try your fix with some of them. It would be good if it worked as you removed that ugly part.

**Comment by tibbi** [comment]
Seems to be working fine in my cases, we will see real results once it gets published. Thanks

**Pull request merged**
