### PR TITLE
Rename method `getDatesWeekDateTime()` to `getFirstDayOfWeek()`

### PR DESCRIPTION
**Pull request by Naveen3Singh**

### CODE REVIEW

**Comment by tibbi** [comment]
so we are ready for using any day of the week as the first day? For https://github.com/SimpleMobileTools/Simple-Calendar/issues/582 :) It would need a new setting instead of the current toggle.

**Comment by WessellUrdata** [comment]
> so we are ready for using any day of the week as the first day? For #582 :) It would need a new setting instead of the current toggle.

It's doable, just keep the Joda-time's Monday as first day behavior in mind ☺️
One problem that I can think of is the calculation of the week number, but that shouldn't be too hard to deal with

**Comment by tibbi** [comment]
ok :)

**Comment by Naveen3Singh** [comment]
agreed, shouldn't be too hard to do.

**Pull request merged**
