### PR TITLE
Add Bengali translation

### PR DESCRIPTION
**Pull request by nowshad-hasan**

### CODE REVIEW

**Comment by tibbi** [comment]
cool, thanks. I dont see such a language on Google Play yet, guess it isnt supported so I cannot apply the app descriptions there.

**Comment by nowshad-hasan** [comment]
I think it's supported. I'm using Android 10 on my Nokia 7 Plus which is stock android. It's very easy to change the language from settings to Bengali. You can try it on your phone too.

**Comment by tibbi** [comment]
BN belongs to Bangla on Google Play. Is that it?

**Comment by nowshad-hasan** [comment]
Yap, Bangla and Bengali are the same.

**Comment by tibbi** [comment]
ok thanks, I applied it

**Pull request merged**
