### PR TITLE
Fixed tablet bug and current day bug

### PR DESCRIPTION
**Pull request by Progern**
Fixed bug with tablet landscape-view year view
Fixed bug with left-shifted current day circle.

### CODE REVIEW

**Comment by tibbi** [comment]
Ill check the functionality once I get home, for now I see just some styling issues. Please keep the current code formatting which is the default Android Studio one, dont add/remove spaces around brackets and in xml files. Also add the yearly_month_xxx_padding in the regular dimens.xml file too.

**Comment by Progern** [comment]
Okay, I've got it. I am using plain Android Studio code formatting tool and I haven't added any format-pattern files. I've reviewed and reformatted code in changed files and added the dimens param. Please check.

**Comment by tibbi** [comment]
all those changes in the old fragment_year.xml are unnecessary

**Comment by tibbi** [comment]
the yearly_month_right_padding isnt even used.
The new landscape layout isnt needed, as the only change is the added yearly_month_left_padding . Just add yearly_month_left_padding in the portrait too and set it to 0 in dimens.xml. The column count change should be somehow in the code, I dont want to create an unnecessary new file land/fragment_year.

**Comment by Progern** [comment]
Okay, I will make these changes today. Sorry for the long delay.

**Comment by Progern** [comment]
I've removed unnecessary fields.
Without land/fragment_year it becomes a bit broken and I've done some research and it's usually a good practice to have two layouts - for landscape and portrait in Android development.

**Comment by tibbi** [comment]
you are still doing many unnecessary style changes at the old fragment_year.xml by adding spaces , also at https://github.com/Progern/Simple-Calendar/commit/3147be1d9b762941d67e9fd36a1e95bc344c45e0#diff-03fcc9fcaef9b15802f9a9a6ff1f569dR87 change the constants only for landscape mode, I dont want to change to mobile UI. The duplicated file can stay then, Ill figure something out for it. Thanks

**Comment by tibbi** [comment]
also if the new layout is layout-land, the new dimensions might need to be dimens-land too, not dimens-sw600dp. Not sure about that, just consider it. Check what works better portrait tablets.

**Comment by tibbi** [comment]
Alright thanks for the fixes, Ill do the last small touches.

**Pull request merged**
