### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by 10cents**
Should be ok by now.
BTW: Have used \  for the ' character, I guess that is necessary? See line 173-177.

### CODE REVIEW

**Comment by tibbi** [comment]
Hey, nice. Yes escaping apostrophes is necessary, I just added it to the translation guide notes at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . Thanks

**Comment by tibbi** [comment]
Please shorten the app short description at the bottom, it is 82 characters long, while the max is 80. Thanks

**Comment by 10cents** [comment]
Hm, not sure what you mean by 'Please shorten the app short description at the bottom with a new pull request, it is 82 characters long, while the max is 80.'? I really do not feel at home here :)

**Comment by 10cents** [comment]
And what does it mean: "You’re all set—the 10cents:patch-2 branch can be safely deleted. " - ?

**Comment by tibbi** [comment]
You have to make "En simpel kalender med begivenheder, en widget der kan tilpasses og uden reklamer." by 2 characters shorter, it is too long :)
Not sure where do you see it, hard to explain to a non-IT guy :p By this pull request you have created an own version of the repository with your edits, which you submited to me. I accepted it, so you can remove your own version.

**Comment by 10cents** [comment]
Originally my intension was to make a translation and then come back later to proof read it. But I havn't found any places to edit my contribution, so I started all over again. So how do I edit the string?

**Comment by 10cents** [comment]
Found it!

**Pull request merged**
