### PR TITLE
Phase One release for Issue #620

### PR DESCRIPTION
**Pull request by jtj9817**
When the application starts, a new Thread is started in the background after checking for PERMISSION_READ_CONTACTS. However, I believe that this can be further improved if Kotlin Coroutines were used instead of the generic Thread lambda function.

### CODE REVIEW

**Comment by tibbi** [comment]
please stick to the code style used in the project, this looks way off. Thanks

**Comment by jtj9817** [comment]
I tried to follow the code style used in the project since there's no official cod estyle guide in the README file of the repository. Please tell me how I can improve the code style for this pull request so I can continue working on it. If there's a guideline online that you use that I should also follow, please post it. Thanks!

**Comment by tibbi** [comment]
it doesnt need to be in the readme, just read the code in other files, for gods sake

**Comment by tibbi** [comment]
sorry, but this is just getting worse. Thanks for the effort though.

**Pull request closed without merging**
