### PR TITLE
make getDateFromCode and getDayTitle locale aware

### PR DESCRIPTION
**Pull request by Honk2**
fixes SimpleMobileTools/Simple-Calendar#969

### CODE REVIEW

**Comment by tibbi** [comment]
that doesnt solve the situation, the app needs a "Change date format", like some apps have. This would work really weird.

**Comment by Honk2** [comment]
I am not sure what a "change date format" option should look like.
Usually a user likes to see dates and numbers formatted to a specific locale. Typically the one your are familiar with. Therefore I think using locale functions is a good approach. 
Of cause it could be a nice feature to add an option to select whether to use the system default locale or a specific one.
Would this be acceptable and solve the situation?

**Comment by tibbi** [comment]
you can see the date format picker for example in the gallery. Also with your solution the user would see 2020 at every date, which would be really annoying and ugly.

**Comment by Honk2** [comment]
Ah, just checked the date format picker and got your point.

Still I would suggest to use locale functions and let the user select the short or long version of the selected locale. This would include the choices in the format picker and prevent requests for more formats, because they are all included.

The missing year is actually why I still stick to the default (Lineage) calender. If this is annoying and ugly is a matter of taste. Some like to hide any redundant data, others like me prefer consistent layouts as in the default calender.

Anyway I see that a comprehensive date format picker with preferences for the different views is the key and a real advantage for your calender.

**Pull request closed without merging**
