### PR TITLE
Customize weekends highlight color

### PR DESCRIPTION
**Pull request by ikazuhiro**
This PR would fix https://github.com/SimpleMobileTools/Simple-Calendar/issues/1535

### CODE REVIEW

**Comment by tibbi** [comment]
should be good, but the settings have just been redesigned, so please resolve the merge conflict and move the setting item up, as the last item at the "Color customization" section. Also change the string to "Color of highlighted weekends" and add it to all string files.

**Comment by tibbi** [comment]
I just added the new string to speed up the translations

**Comment by ikazuhiro** [comment]
Thank you for reviewing.

> so please resolve the merge conflict and move the setting item up, as the last item at the "Color customization" section.

Done.  But when I toggle "Highlight weekends on some views", all sections except "Color customization" are moved up or down by "Color of highlighted weekends" item.  I thik moving "General" section to the top of settings would be better when this PR is merged.

**Comment by tibbi** [comment]
will take a look at it, to see how it behaves

**Comment by tibbi** [comment]
ye I moved it down under the checkbox, should be good. Thanks

**Pull request merged**
