### PR TITLE
Add event transparency

### PR DESCRIPTION
**Pull request by yue-dongchen**
Discussed to be a useful feature in #909, event transparency has been added in this pull request. The two states are "occupied" (busy) and "available" (free). The icons are from Google's Material Design, licensed under Apache. The `IcsImporter` and `IcsExporter` have been properly implemented and tested. The "Busy" and "Free" strings have been translated in `zh-CN`, `zh-TW` and `de` (the ones I'm certain about).

Feel free to edit this if you think the code style be better.

### CODE REVIEW

**Comment by yue-dongchen** [comment]
@tibbi Here's an image.

 Event Transparency

**Comment by tibbi** [comment]
this whole thing should be visible only at CalDAV synced events like attendees, else it doesnt make much sense

**Comment by yue-dongchen** [comment]
Yes. It's only visible in CalDAV events.

**Comment by yue-dongchen** [comment]
My bad. I'll set its visibility. Didn't realise it's still visible.

**Comment by yue-dongchen** [comment]
@tibbi  That's now fixed.

**Comment by tibbi** [comment]
1. you aren't handling database upgrading from older app version well, it is crashing at upgrade. You added a new field to the Event model
2. the Busy/Available label should be a new field at the event details screen, do not mix it with attendees

**Comment by yue-dongchen** [comment]
I'll look into the first issue.

Regarding the interface design, I think it would make sense for the label to be there, since that's how the notification for the reminders are positioned. It's separate from the contact inputs and doesn't duplicate when adding multiple attendees. The event transparency is quite related to attendees, in my opinion. But since this is your app, I'll change the position if you want. To clarify, do you want it to occupy a new "line"?

**Comment by tibbi** [comment]
sure, setting the busy/available labels at attendees doesnt make much sense

**Comment by yue-dongchen** [comment]
@tibbi The database migration is now properly handled. Below is the new position:
Availability

**Comment by tibbi** [comment]
if I create an event in Google Calendar and set myself as Free, it is shown as Busy in Simple Calendar. Guess you are not checking the status correctly. Also please rename the new strings to status_free and status_busy. I added them like that into the master already so that people can translate it meanwhile. Thanks

**Comment by yue-dongchen** [comment]
Thanks a lot. Sorry for my lack of experience. I definitely learnt something there (to carefully test everything). I've created another commit to add the translations back in.

**Comment by tibbi** [comment]
alright, guess it will work well like this. Thanks

**Pull request merged**
