### PR TITLE
Don't set EXDATE on recurrence exceptions

### PR DESCRIPTION
**Pull request by evan-goode**
Resolves (or at least improves):
- #1538
- https://github.com/bitfireAT/davx5-ose/discussions/66
- https://github.com/Kozea/Radicale/issues/1264
- May also resolve some of the issues described in #1983.

The "EXDATE" property is only meant to be set on events with the "RRULE" property. See discussion in #1538, especially the response from DAVx5 support listed in the first comment.

I tried also setting STATUS_CANCELED on these recurrence exception events, but DAVx5 would sometimes no longer recognize them as belonging to the parent event and would give the child events different UIDs, which is undesirable. It seems like it works great to just leave out the EXDATE.

I have not tested this patch with other CalDAV setups, but it solves the problem for me on DAVx5+Radicale.

### CODE REVIEW

**Comment by tibbi** [comment]
@Naveen3Singh can you please test this?

**Comment by Naveen3Singh** [comment]
It works. Repeating exceptions are no longer rejected by Radicale and Mailbox. Nextcloud works just as before.

> I tried also setting STATUS_CANCELED on these recurrence exception events, but DAVx5 would sometimes no longer recognize them as belonging to the parent event and would give the child events different UIDs, which is undesirable

I couldn't reproduce the UID issue when setting the status to STATUS_CANCELLED but as much as I could test, deletion seems to work fine without the canceled event status.

There are still other issues related to recurring event exceptions. For example, when a recurring event occurrence is modified (not deleted) by some other calendar app, the events disappear in Simple Calendar as mentioned in https://github.com/SimpleMobileTools/Simple-Calendar/issues/1017
Other related/similar issues: https://github.com/SimpleMobileTools/Simple-Calendar/issues/981 (reproducible with local events too), https://github.com/SimpleMobileTools/Simple-Calendar/issues/950, https://github.com/SimpleMobileTools/Simple-Calendar/issues/735, https://github.com/SimpleMobileTools/Simple-Calendar/issues/1358

**Comment by tibbi** [comment]
alright, thanks. Maybe @Naveen3Singh you could take at those related repeating issues, will create a task for them

**Comment by Naveen3Singh** [comment]
> alright, thanks. Maybe @Naveen3Singh you could take at those related repeating issues, will create a task for them

Sure :)

**Pull request merged**
