### PR TITLE
Create values-uk/strings.xml

### PR DESCRIPTION
**Pull request by motomoto7**
Added values-uk. Copied strings from values-ua and slightly modified <string name="app_long_description"> (deleted dashes) since <string name="pro_app_refund"> from Simple-Commons was missing the first part in Ukrainian App Store (not sure maybe the limit was reached in a longer app description)

### CODE REVIEW

**Comment by motomoto7** [comment]
Is there anything I should do to delete values-ua?

**Comment by tibbi** [comment]
use "ua" for ukrainian strings please, not "uk"

**Comment by tibbi** [comment]
Actually nevermind, "uk" is the proper one. I got confused there. Ill delete the ua, thanks.

**Comment by motomoto7** [comment]
The long description for Simple Calendar from Google Playstore contains a part of a string from Simple Commons, marked in orange
https://github.com/SimpleMobileTools/Simple-Commons/blob/29a63bf980b53bbf821848160500bc33c648d1bb/commons/src/main/res/values-uk/strings.xml#L665 
Screenshot_2019-05-24-15-33-24_

**Comment by tibbi** [comment]
and what is the issue there? It is a common sentence shared between the pro apps and their free versions

**Comment by motomoto7** [comment]
In Ukrainian Google Playstore the sentence in orange starts with ''hours, you will automatically be refunded...'' It should start with ''Don\'t forget that if you uninstall any paid app within 2 hours...''. You should add ''Пам\'ятайте: якщо ви видалите будь-який платний додаток протягом 2'' from  https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values-uk/strings.xml line 665.

**Comment by tibbi** [comment]
updated, thanks

**Comment by motomoto7** [comment]
Yep, fixed now. Could you please also update Ukrainian translation for the app. Thanks.

**Comment by tibbi** [comment]
which part of the translation you mean?

**Comment by motomoto7** [comment]
Days of the week, days of the months, most of the settings in the app menu are in English. 
App version 6.5.0. Android vers. 9
Screenshot_20190531-001401
Screenshot_20190531-001508
Screenshot_20190531-001522
Screenshot_20190531-001536
Screenshot_20190531-001549
Screenshot_20190531-001601
Screenshot_20190531-001616
Screenshot_20190531-001812
Screenshot_20190531-001841

**Comment by tibbi** [comment]
well the app hasnt been updated yet

**Pull request merged**
