### PR TITLE
Februar 29th #1081 and Check a leap year related issue #1056

### PR DESCRIPTION
**Pull request by Honk2**
This patch will handle the 29th of February correctly on yearly recurring events.
On non leap years the event will be on the 28th but on the 29th on leap years.

### CODE REVIEW

**Comment by tibbi** [comment]
lets rather hide such events on nonleap years and only show them if february 29 is available. Thats how it works in Google Calendar and thus people expect that behaviour.

**Comment by Honk2** [comment]
I just realized, that I did things wrong.
On non leap years, a recurring event originally on Feb 29th, must move to March 1st.
I do not know the google calendar, but think that it works like that. Therefore I need to modify the patch....

**Comment by Honk2** [comment]
ok, now the behaviour is as it should be.
At least Birthdays are now shown always on the correct day.

**Comment by tibbi** [comment]
I dont want to show Feb 29 events on March 1, it just sounds bad. Lets stick to the way Google Calendar works in such cases, people are used to that.

**Comment by Honk2** [comment]
ok, I respect this. Although it seems that in most countries, the 1st of March is the legal data for time spans in non leap years.
Funny that the google calendar behaves like that.

**Pull request closed without merging**
